export const notes = [
    {
        name: 'Shopping List',
        created: 'September 17, 2022',
        category: 'task', 
        content: 'Carrot, Lemon, Kvas', 
        dates: '',
        edit: '',
        archive: '',
        delete: '',
    },
    {
        name: 'Sons Gimnastic Section',
        created: 'September 17, 2022',
        category: 'random', 
        content: 'Sons have section 17/9/2022 16:00, 20/9/2022', 
        dates: '',
        edit: '',
        archive: '',
        delete: '',
    },
    {
        name: 'Confucius',
        created: 'September 12, 2022',
        category: 'quote', 
        content: 'Everything has beauty, but not everyone sees it.', 
        dates: '',
        edit: '',
        archive: '',
        delete: '',
    },
    {
        name: 'New Illustration',
        created: 'June 27, 2022',
        category: 'idea', 
        content: 'Summer illustration for digital magazin', 
        dates: '',
        edit: '',
        archive: '',
        delete: '',
    },
    {
        name: 'Bill Keane',
        created: 'July 12, 2022',
        category: 'quote', 
        content: 'Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.', 
        dates: '',
        edit: '',
        archive: '',
        delete: '',
    },
    {
        name: 'Books',
        created: 'May 15, 2022',
        category: 'task', 
        content: 'Read some book about JS, React and Digital Illustration', 
        dates: '',
        edit: '',
        archive: '',
        delete: '',
    },
    {
        name: 'Meet Mom',
        created: 'September 16, 2022',
        category: 'random', 
        content: 'Mom is coming 26/9/2022', 
        dates: '',
        edit: '',
        archive: '',
        delete: '',
    },
];

export const category = ['task', 'idea', 'quote', 'random']; 

export const tableTitle = ['name', 'created', 'category', 'content', 'dates', 'edit', 'archive', 'delete'];
